[build]
  command = "npm run build"
  publish = "dist/"
  NODE_ENV = "8.9.0"
  Functions = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
