backend:
  name:              git-gateway
  branch:            master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts for GitHub
# publish_mode:      editorial_workflow

media_folder:        "images" # Media files will be stored in the repo under images

# Replace URL with your Netlify or Custom domain to enable CMS previews
site_url:            https://demo-streamsites.netlify.com
display_url:         https://demo-streamsites.netlify.com

show_preview_links:  true

collections:
  - name:            "blog"
    label:           "Blog"
    label_singular:  "Blog Post"
    description:     "Create or edit a blog post"
    folder:          "site/blog"
    create:          true
    slug:            "{{fields.slug}}"
    preview_path:    "blog/{{fields.slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Set as draft?", name: "eleventyExcludeFromCollections", widget: "boolean", default: false, hint: "Default is public. Toggle right to make it a draft, left to make it public." }
      - { label: "Tag", name: "tags", widget: "list", hint: "Apply tags to create archives of posts that are similar and/or related. Separate multiple with a comma: i.e. Tag 1, Tag 2, Tag 3" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false, media_library: {config:{multiple: false}} }
      - { label: "Image Caption", name: "image_caption", widget: "string", required: false, hint: "Describe this image for anyone who can't see it. Also a great place to give credit where credit is due." }
      - { label: "TL;DR", name: "tldr", widget: "text", hint: "A short description of this post for people who don't want to read. Shown at the beginning of the post." }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
          - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
      - { label: "Template", name: "layout", widget: "hidden", default: "post" }
  - name:            "page"
    label:           "Pages"
    label_singular:  "Page"
    description:     "Create or edit a page"
    folder:          "site/page"
    create:          true
    filter:          { field: "page_type", value: "default" }
    slug:            "{{fields.slug}}"
    preview_path:    "{{fields.slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false, media_library: {config:{multiple: false}} }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Make this page public?", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, hint: "Default is public. Toggle right to make public, left to make private." }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
          - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
      - { label: "Template", name: "layout", widget: "hidden", default: "default" }
      - { label: "Page Type", name: "page_type", widget: "hidden", default: "default" }
  - name:            "modules"
    label:           "Modules"
    label_singular:  "Module"
    description:     "Configure and customize modules"
    create:          false
    slug:            "{{slug}}"
    preview_path:    "{{fields.slug}}"
    files:
      - label:       "About"
        name:        "about"
        file:        "site/page/about.md"
        slug:        {{fields.slug}}
        preview:     true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string", default: "about" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Contact Form", name: "form", widget: "boolean", default: true, hint: "Should the page display a contact form?" }
          - { label: "Use this module?", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, hint: "Default is enabled. Toggle right to enable, left to disable." }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
              - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
          - { label: "Template", name: "layout", widget: "hidden", default: "layouts/about.njk" }
      - label:       "Author Box"
        name:        "author"
        file:        "site/globals/author.json"
        fields:
          - { label: "Author Box: On or Off?", name: "display", widget: "boolean", default: true, hint: "Choose whether or not to display the Author Box at the end of a blog post." }
          - { label: "Name", name: "name", widget: "string", hint: "The name you want people to call you, such as your Twitch name or IRL name." }
          - { label: "Short Bio", name: "bio", widget: "text", hint: "A short description of yourself to include at the end of blog posts." }
          - { label: "Avatar", name: "avatar", widget: "image", media_library: {config:{multiple: false}}, hint: "An image of you/your logotype. For best results use a square image at 500x500 pixels."}
      - label:       "Contact"
        name:        "contact"
        file:        "site/page/contact.md"
        slug:        {{fields.slug}}
        preview:     true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string", default: "contact" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Contact Form", name: "form", widget: "boolean", default: true, hint: "Should the page display a contact form?" }
          - { label: "Use this module?", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, hint: "Default is enabled. Toggle right to enable, left to disable." }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
              - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
          - { label: "Template", name: "layout", widget: "hidden", default: "layouts/contact.njk" }
      - label:       "404 Page"
        name:        "404"
        file:        "site/page/404.md"
        slug:        {{fields.slug}}
        preview:     true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string", default: "404" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
              - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
          - { label: "Template", name: "layout", widget: "hidden", default: "layouts/404.njk" }
      - label:       "Privacy Policy"
        name:        "privacy"
        file:        "site/page/privacy-policy.md"
        slug:        {{fields.slug}}
        preview:     true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Effective Date", name: "date", widget: "datetime" }
          - { label: "Slug", name: "slug", widget: "hidden", default: "privacy" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Use this module?", name: "eleventyExcludeFromCollections", widget: "boolean", default: true, hint: "Default is enabled. Toggle right to enable, left to disable." }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
              - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
          - { label: "Template", name: "layout", widget: "hidden", default: "privacy" }
  - name:            "linkinbio"
    label:           "Link In Bio"
    label_singular:  "Link In Bio"
    description:     "Edit your Link in Bio content and/or links"
    create:          false
    slug:            "{{slug}}"
    preview_path:    "{{fields.slug}}"
    files:
      - label:       "Content"
        name:        "linkinbio_content"
        file:        "site/page/linkinbio.md"
        preview:     true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string", default: "link-in-bio" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Meta Title", name: "meta_title", widget: "string", required: false, hint: "A title to display on a Search result. (What do you want Google to see?)" }
              - { label: "Meta Description", name: "excerpt", widget: "text", required: false, hint: "A short description to tease this in a Search or Social Media preview." }
          - { label: "Template", name: "layout", widget: "hidden", default: "layouts/linkinbio.njk" }
      - label:       "Links"
        name:        "linkinbio_links"
        file:        "site/globals/linkinbio.json"
        preview:     true
        fields:
          - label:   "Add a link"
            name:    "linkinbio"
            widget:  "list"
            fields:
              - { label: "Label", name: "text", widget: "string", hint: "What should the text say?" }
              - { label: "Link", name: "link", widget: "string", hint: "Where should the link go? Include the https:// if you want to guarantee it works." }
  - name:            "powerups"
    label:           "Power Ups"
    label_singular:  "Power Up"
    description:     "Manage your Power Ups"
    create:          false
    editor:
      preview:       false
    files:
      - label:       "Twitch"
        name:        "twitch"
        file:        "site/globals/twitch.json"
        preview:     false
        fields:
          - { label: "Twitch Handle", name: "handle", widget: "string", hint: "What is your Twitch handle?" }
  - name:            "settings"
    label:           "Settings"
    description:     "Edit your global settings."
    extension:       "json"
    format:          "json"
    create:          false
    editor:
      preview:       false
    files:
      - label:       "Branding"
        name:        "site"
        file:        "site/globals/site.json"
        preview:     false
        fields:
          - { label: "Brand Name", name: "name", widget: "string", hint: "The name of your brand, community, or just your Twitch name." }
          - { label: "Live URL", name: "url", widget: "string", hint: "What is the URL of your site? I.e. https://streamsites.xyz" }
          - { label: "Email address", name: "email", widget: "string", hint: "This is required for your privacy policy. Where should people reach you? Don't have an email - Sidemail is great!" }
          - { label: "Logo", name: "logo", widget: "image", media_library: {config:{multiple: false}}}
          - { label: "Favicon", name: "favicon", widget: "image", media_library: {config:{multiple: false}}}
          - label:   "Theme"
            name:    "colors"
            widget:  "object"
            fields:
              - { label: "Main Color", name: "main", widget: "select", default: "purple", options: ["red", "orange", "yellow", "teal", "blue", "indigo", "purple", "pink"], hint: "Pick a main color for your site." }
              - { label: "Accent Color", name: "accent", widget: "select", default: "pink", options: ["red", "orange", "yellow", "teal", "blue", "indigo", "purple", "pink"], hint: "Pick a secondary color for your site. Used on buttons and other accents." }
      - label:       "Navigation"
        name:        "nav"
        file:        "site/globals/navigation.json"
        preview:     false
        fields:
          - label:    "Logo"
            name:     "nav_logo"
            widget:   "boolean"
            default:   true
            hint:     "Choose whether or not to display your logo in the site header. You can upload/change your logo in Settings: Branding."
          - label:    "Menu Links"
            label_singular: "Menu Link"
            name:     "main"
            widget:   "list"
            fields:
              - { label: "Label", name: "label", widget: "string", hint: "What text should be displayed?" }
              - { label: "Link", name: "url", widget: "string", hint: "What should this link to?" }
          - label:   "Menu Button"
            name:    "nav_button"
            widget:  "object"
            fields:
              - { label: "Button Text", name: "button_text", widget: "string", hint: "Something clickbaity" }
              - { label: "Button Link", name: "button_link", widget: "string", hint: "Where should the link go? Twitch? Your Discord? Include the https:// if you want to guarantee it works." }
      - label:       "SEO"
        name:        "seo"
        file:        "site/globals/seo.json"
        preview:     false
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", required: false, hint: "Customize the title a search engine will see." }
          - { label: "Site Description", name: "site_description", widget: "text", required: false, hint: "Write a default description to appear on posts/pages via search results when a custom one does not exist." }
          - label:   "Default Social Share Images"
            name:    "images"
            widget:  "object"
            fields:
              - { label: "Open Graph Image", name: "og", widget: "image", media_library: { config: { multiple: false } }, hint: "This is the image used by Facebook and other Open Graph networks." }
              - { label: "Twitter Card Image", name: "twitter_og", widget: "image", media_library: { config: { multiple: false } }, hint: "This is the image used by Twitter to make a large Twitter Card link preview." }
      - label:       "Social Links"
        name:        "social"
        file:        "site/globals/social.json"
        fields:
          - label:   "Social Links"
            label_singular: "Social Link"
            name:    "social_links"
            widget:  "object"
            fields:
              - { label: "Twitter", name: "twitter", widget: "string", hint: "https://twitter.com/yourhandle" }
              - { label: "LinkedIn", name: "linkedin", widget: "string", hint: "https://linkedin.com/in/yourhandle" }
              - { label: "Facebook", name: "facebook", widget: "string", hint: "https://facebook.com/yourpagename" }
  - name:            "custom"
    label:           "Custom Modules"
    description:     "Manage your custom modules"
    extension:       "json"
    format:          "json"
    create:          false
    editor:
      preview:       false
    files:
      - label:       "CTA Buttons"
        name:        "ctas"
        file:        "site/globals/ctas.json"
        preview:     false
        fields:
          - label:    "Create a button"
            name:     "buttons"
            widget:   "list"
            fields:
              - { label: "Button Text", name: "button_text", widget: "string", hint: "What text should be displayed?" }
              - { label: "Button Link", name: "button_link", widget: "string", hint: "What should this link to?" }
