backend:
  name:              git-gateway
  branch:            master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts for GitHub
# publish_mode:      editorial_workflow

media_folder:        "images" # Media files will be stored in the repo under images

# Replace URL with your Netlify or Custom domain
# to enable CMS previews
site_url:            https://demo-streamsites.netlify.com
display_url:         https://demo-streamsites.netlify.com

show_preview_links:  false

collections:
  - name:            "blog"
    label:           "Blog"
    label_singular:  "Blog"
    description:     "Create a blog post."
    folder:          "site/blog"
    create:          true
    slug:            "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image", media_library: {config:{multiple: false}} }
      - { label: "Image Caption", name: "image_caption", widget: "string", hint: "Describe this image for anyone who can't see it. Also a great place to give credit where credit is due." }
      - { label: "Excerpt", name: "excerpt", widget: "string", hint: "A short description to tease this in a Search or Social Media preview." }
      - { label: "TL;DR", name: "tldr", widget: "string", hint: "A short description of this post for people who don't want to read. Shown at the beginning of the post." }
      - { label: "Tag", name: "tags", widget: "string", hint: "Supports 1 Tag right now. Pick a key word this post should be associated with so it can be grouped with others of the same tag." }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Template", name: "layout", widget: "hidden", default: "post" }
  - name:            "page"
    label:           "Pages"
    label_singular:  "Page"
    description:     "Create a new page."
    folder:          "site/page"
    create:          true
    slug:            "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", hint: "A title to display on a Search result. (What do you want Google to see?)" }
      - { label: "Meta Description", name: "meta_description", widget: "string", hint: "A short description to tease this in a Search or Social Media preview." }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Template", name: "layout", widget: "hidden", default: "default" }
  - name:            "settings"
    label:           "Settings"
    description:     "Edit your global settings."
    extension:       "json"
    format:          "json"
    create:          false
    editor:
      preview:       false
    files:
      - label:       "Brand Settings"
        name:        "site"
        file:        "site/globals/site.json"
        preview:     false
        fields:
          - { label: "Brand Name", name: "name", widget: "string", hint: "The name of your brand, community, or just your Twitch name." }
          - { label: "Live URL", name: "url", widget: "string", hint: "What is the URL of your site? I.e. https://streamsites.xyz" }
          - { label: "Favicon", name: "favicon", widget: "image", media_library: {config:{multiple: false}}}
          - label:   "Theme"
            name:    "colors"
            widget:  "object"
            fields:
              - { label: "Main Color", name: "main", widget: "select", default: "purple", options: ["red", "orange", "yellow", "teal", "blue", "indigo", "purple", "pink"], hint: "Pick a main color for your site." }
              - { label: "Accent Color", name: "accent", widget: "select", default: "pink", options: ["red", "orange", "yellow", "teal", "blue", "indigo", "purple", "pink"], hint: "Pick a secondary color for your site. Used on buttons and other accents." }
      - label:       "Social Media"
        name:        "social"
        file:        "site/globals/social.json"
        fields:
          - label:   "Social Sharing Images"
            name:    "images"
            widget:  "object"
            fields:
              - { label: "Open Graph Image", name: "og", widget: "image", media_library: { config: { multiple: false } }, hint: "This is the image used by Facebook and other Open Graph networks." }
              - { label: "Twitter Image", name: "twitter_og", widget: "image", media_library: { config: { multiple: false } }, hint: "This is the image used by Twitter to make a large Twitter Card link preview." }
          - label:   "Social Links"
            name:    "social_links"
            widget:  "object"
            fields:
              - { label: "Twitter", name: "twitter", widget: "string", hint: "https://twitter.com/yourhandle" }
              - { label: "LinkedIn", name: "linkedin", widget: "string", hint: "https://linkedin.com/in/yourhandle" }
              - { label: "Facebook", name: "facebook", widget: "string", hint: "https://facebook.com/yourpagename" }

      - label:       "Profile Settings"
        name:        "author"
        file:        "site/globals/author.json"
        fields:
          - { label: "Name", name: "name", widget: "string", hint: "The name you want people to call you, such as your Twitch name or IRL name." }
          - { label: "Email", name: "email", widget: "string", hint: "An email someone can reach you at. Example: hi@streamsites.xyz" }
          - { label: "Twitch Display Name", name: "twitch_handle", widget: "string", hint: "Your Twitch Handle, this is case sensitive. THANKS TWITCH!" }
          - { label: "Twitter Handle", name: "twitter_handle", widget: "string", hint: "Your Twitter handle" }
          - { label: "Avatar", name: "avatar", widget: "image", media_library: {config:{multiple: false}}, hint: "An image of you/your logotype. For best results use a square image at 500x500 pixels."}
          - { label: "Short Bio", name: "bio", widget: "string", hint: "A short description of yourself to include at the end of blog posts." }
#      - label:       "Link In Bio"
#        name:        "linkinbio"
#        file:        "site/globals/linkinbio.json"
#        create:       true
#        fields:
#          - label:   "Add a Link"
#            name:    "linksinbio"
#            widget:  "list"
#              fields:
#                - { label: "Text", name: "text", widget: "string", hint: "What should the text say?" }
#                - { label: "Link", name: "link", widget: "string", hint: "Where should the link go? Include the https:// if you want to guarantee it works." }
