backend:
  name:              git-gateway
  branch:            master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts for GitHub
# publish_mode:      editorial_workflow

media_folder:        "images" # Media files will be stored in the repo under images

# Replace URL with your Netlify or Custom domain
# to enable CMS previews
site_url:            https://demo-streamsites.netlify.com
display_url:         https://demo-streamsites.netlify.com

show_preview_links:  false

collections:
  - name:            "blog"
    label:           "Blog"
    label_singular:  "Blog"
    description:     "Create a blog post."
    folder:          "site/blog"
    create:          true
    slug:            "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image", media_library: {config:{multiple: false}} }
      - { label: "Image Caption", name: "image_caption", widget: "string", hint: "Describe this image for anyone who can't see it. Also a great place to give credit where credit is due." }
      - { label: "Excerpt", name: "excerpt", widget: "string", hint: "A short description to tease this in a Search or Social Media preview." }
      - { label: "TL;DR", name: "tldr", widget: "string", hint: "A short description of this post for people who don't want to read. Shown at the beginning of the post." }
      - { label: "Tag", name: "tags", widget: "string", hint: "Supports 1 Tag right now. Pick a key word this post should be associated with so it can be grouped with others of the same tag." }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Template", name: "layout", widget: "hidden", default: "post" }
  - name:            "page"
    label:           "Pages"
    label_singular:  "Page"
    description:     "Create a new page."
    folder:          "site/page"
    create:          true
    slug:            "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", hint: "A title to display on a Search result. (What do you want Google to see?)" }
      - { label: "Meta Description", name: "meta_description", widget: "string", hint: "A short description to tease this in a Search or Social Media preview." }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Template", name: "layout", widget: "hidden", default: "default" }
  - name:            "linkinbio"
    label:           "Link In Bio"
    label_singular:  "Link In Bio"
    description:     "Edit a specialty page."
    create:          false
    slug:            "{{slug}}"
    files:
      - label:       "Content"
        name:        "linkinbio_content"
        file:        "site/page/linkinbio.md"
        preview:     true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Template", name: "layout", widget: "hidden", default: "layouts/linkinbio.njk" }
          - { label: "Meta Title", name: "meta_title", widget: "string", hint: "A title to display on a Search result. (What do you want Google to see?)" }
          - { label: "Meta Description", name: "meta_description", widget: "string", hint: "A short description to tease this in a Search or Social Media preview." }
          - { label: "Slug", name: "slug", widget: "string", default: "link-in-bio" }
      - label:       "Links"
        name:        "linkinbio_links"
        file:        "site/globals/linkinbio.json"
        fields:
          - label:   "Add a link"
            name:    "linkinbio"
            widget:  "list"
            fields:
              - { label: "Label", name: "text", widget: "string", hint: "What should the text say?" }
              - { label: "Link", name: "link", widget: "string", hint: "Where should the link go? Include the https:// if you want to guarantee it works." }
  - name:            "settings"
    label:           "Settings"
    description:     "Edit your global settings."
    extension:       "json"
    format:          "json"
    create:          false
    editor:
      preview:       false
    files:
      - label:       "Brand Settings"
        name:        "site"
        file:        "site/globals/site.json"
        preview:     false
        fields:
          - { label: "Brand Name", name: "name", widget: "string", hint: "The name of your brand, community, or just your Twitch name." }
          - { label: "Live URL", name: "url", widget: "string", hint: "What is the URL of your site? I.e. https://streamsites.xyz" }
          - { label: "Logo", name: "logo", widget: "image", media_library: {config:{multiple: false}}}
          - { label: "Favicon", name: "favicon", widget: "image", media_library: {config:{multiple: false}}}
          - label:   "Theme"
            name:    "colors"
            widget:  "object"
            fields:
              - { label: "Main Color", name: "main", widget: "select", default: "purple", options: ["red", "orange", "yellow", "teal", "blue", "indigo", "purple", "pink"], hint: "Pick a main color for your site." }
              - { label: "Accent Color", name: "accent", widget: "select", default: "pink", options: ["red", "orange", "yellow", "teal", "blue", "indigo", "purple", "pink"], hint: "Pick a secondary color for your site. Used on buttons and other accents." }
      - label:       "Social Media"
        name:        "social"
        file:        "site/globals/social.json"
        fields:
          - label:   "Social Sharing Images"
            name:    "images"
            widget:  "object"
            fields:
              - { label: "Open Graph Image", name: "og", widget: "image", media_library: { config: { multiple: false } }, hint: "This is the image used by Facebook and other Open Graph networks." }
              - { label: "Twitter Image", name: "twitter_og", widget: "image", media_library: { config: { multiple: false } }, hint: "This is the image used by Twitter to make a large Twitter Card link preview." }
          - label:   "Social Links"
            name:    "social_links"
            widget:  "object"
            fields:
              - { label: "Twitter", name: "twitter", widget: "string", hint: "https://twitter.com/yourhandle" }
              - { label: "LinkedIn", name: "linkedin", widget: "string", hint: "https://linkedin.com/in/yourhandle" }
              - { label: "Facebook", name: "facebook", widget: "string", hint: "https://facebook.com/yourpagename" }

      - label:       "Profile Settings"
        name:        "author"
        file:        "site/globals/author.json"
        fields:
          - { label: "Name", name: "name", widget: "string", hint: "The name you want people to call you, such as your Twitch name or IRL name." }
          - { label: "Email", name: "email", widget: "string", hint: "An email someone can reach you at. Example: hi@streamsites.xyz" }
          - { label: "Avatar", name: "avatar", widget: "image", media_library: {config:{multiple: false}}, hint: "An image of you/your logotype. For best results use a square image at 500x500 pixels."}
          - { label: "Short Bio", name: "bio", widget: "string", hint: "A short description of yourself to include at the end of blog posts." }
      - label:       "Navigation"
        name:        "nav"
        file:        "site/globals/navigation.json"
        preview:     false
        fields:
          - label:    "Add a menu item"
            name:     "main"
            widget:   "list"
            fields:
              - { label: "Label", name: "label", widget: "string", hint: "What text should be displayed?" }
              - { label: "Link", name: "url", widget: "string", hint: "What should this link to?" }
          - label:   "Menu Button"
            name:    "nav_button"
            widget:  "object"
            fields:
              - { label: "Button Text", name: "button_text", widget: "string", hint: "Something clickbaity" }
              - { label: "Button Link", name: "button_link", widget: "string", hint: "Where should the link go? Twitch? Your Discord? Include the https:// if you want to guarantee it works." }
      - label:       "Marketing CTAs"
        name:        "ctas"
        file:        "site/globals/ctas.json"
        preview:     false
        fields:
          - label:   "Menu Button"
            name:    "navigation"
            widget:  "object"
            fields:
              - { label: "Button Text", name: "button_text", widget: "string", hint: "Something clickbaity" }
              - { label: "Button Link", name: "button_link", widget: "string", hint: "Where should the link go? Twitch? Your Discord? Include the https:// if you want to guarantee it works." }
  - name:            "modules"
    label:           "Modules"
    description:     "Configure the modules on your site."
    extension:       "json"
    format:          "json"
    create:          false
    editor:
      preview:       false
    files:
      - label:       "Module Settings"
        name:        "site"
        file:        "site/globals/modules.json"
        preview:     false
        fields:
          - { label: "Author Box", name: "author_box", widget: "boolean", default: true, hint: "Choose whether or not to display the Author Box at the end of a blog post." }
          - { label: "Contact Form", name: "contact_form", widget: "boolean", default: true, hint: "Choose whether or not to display the Contact Form on the Contact Page." }
          - { label: "Use Logo", name: "navigation_logo", widget: "boolean", default: true, hint: "Choose whether or not to display a logo in your site header." }
